- id: format-feature-files
  name: Format feature files
  entry: gherkin_formatter.formatter
  language: python
  language_version: python3
  files: "\\.(feature)$"
  args: []
  description: "Formats Gherkin feature files using gherkin-formatter."
