- id: format-feature-files
  name: Format feature files
  entry: gherkin-formatter
  language: python
  language_version: python3
  types: [gherkin]
  args: []
  description: "Formats Gherkin feature files using gherkin-formatter."
